/*
 * About: Gogole Plus Javascript API (Hybrid for NodeJS and Client Side)
 * Source: <https://github.com/AdminSpot/Google-Plus-javascript-API>
 * Created by: Robert Pitt <https://plus.google.com/110106586947414476573>
 * License Type: Opensource (Free to use and modify without warranty)
*/
(function(){function g(a,b){var c={},e;for(e in a)c[e]=a[e];for(e in b)c[e]=b[e];return c}var f="object"==typeof module;if(!0===f)var h=require("https"),i=require("querystring"),j={host:"www.googleapis.com",port:443,method:"GET"};var d=function(a){if(!a)throw"you must set the api_key when instantiating the object";this.api_key=a};d.prototype.getPerson=function(a,b,c){return this.request("people/"+a,b,c)};d.prototype.listByActivity=function(a,b,c,e){return this.request("activities/"+a+"/people/"+b,
c,e)};d.prototype.listActivities=function(a,b,c){return this.request("people/"+a+"/activities/public",b,c)};d.prototype.getActivity=function(a,b,c){return this.request("activities/"+a,b,c)};d.prototype.searchActivities=function(a,b,c){b.query=a;return this.request("activities",b,c)};d.prototype.listComments=function(a,b,c){return this.request("activities/"+a+"/comments",b,c)};d.prototype.getComment=function(a,b,c){return this.request("comments/"+a,b,c)};d.prototype.searchPeople=function(a,b,c){b.query=
a;return this.request("people",b,c)};d.prototype.request=function(a,b,c){if(f)this.requestNode(a,b,c);else{var e="__GooglePlusApiCallback_"+Math.floor(1000001*Math.random()),d=this.buildRequestURL(a,b,e);console.log(d);window[e]=function(a){a.error?(a.error.request=d,c(a.error,null)):c(null,a)};a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=d;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}};d.prototype.requestNode=function(a,b,c){if(!1===
f)throw"requestNode can only be called within a NodeJS enviroment";a="/plus/v1/"+a+"?"+i.stringify(g(b,{key:this.api_key}));a=g(j,{path:a});h.request(a,function(a){var b="";a.on("data",function(a){b+=a});a.on("close",function(){try{var d=JSON.parse(b);d.error?c(d.error,null):c(null,d)}catch(f){c(Error("Response Code: "+a.statusCode),null)}})}).end()};d.prototype.buildRequestURL=function(a,b,c){b.key=this.api_key;b.callback=c;var a="https://www.googleapis.com/plus/v1/"+a,c=[],d;for(d in b)b.hasOwnProperty(d)&&
c.push(encodeURIComponent(d)+"="+encodeURIComponent(b[d]));return 0<c.length?a+"?"+c.join("&"):a};f?module.exports=d:window.GooglePlusAPI=d})();
